export const ACTION = {code: '28', name: 'action'};
export const ADVENTURE = {code: '12', name: 'adventure'};
export const ANIMATION = {code: '16', name: 'animation'};
export const COMEDY = {code: '35', name: 'comedy'};
export const CRIME = {code: '80', name: 'crime'};
export const DOCUMENTARY = {code: '99', name: 'documentary'};
export const DRAMA = {code: '18', name: 'drama'};
export const FAMILY = {code: '10751', name: 'family'};
export const FANTASY = {code: '14', name: 'fantasy'};
export const HISTORY = {code: '36', name: 'history'};
export const HORROR = {code: '27', name: 'horror'};
export const MUSIC = {code: '10402', name: 'music'};
export const MYSTERY = {code: '9648', name: 'mystery'} ;
export const ROMANCE = {code: '10749', name: 'romance'};
export const SCIENCE_FICTION = {code: '878', name: 'science fiction'};
export const TV_MOVIE = {code: '10770', name: 'tv movie'};
export const THRILLER = {code: '53', name: 'thriller'};
export const WAR = {code: '10752', name: 'war'};
export const WESTERN = {code: '37', name: 'western'};

export const GENRES = [ACTION, ADVENTURE, ANIMATION, COMEDY, CRIME, DRAMA, FAMILY, FANTASY, HORROR, ROMANCE, SCIENCE_FICTION]
